// Generated by https://quicktype.io

export interface AssignmentRoot {
    subpart_id:            number;
    subpart:               Subpart[];
    current_assignment_id: boolean;
}

export interface Subpart {
    id:                           number;
    name:                         string;
    lesson_id:                    number;
    created_at:                   string;
    updated_at:                   string;
    assignments:                  Assignment[];
    pivot:                        Pivot;
    lesson:                       Lesson;
    section_assignment_relations: SectionAssignmentRelation[];
}

export interface Assignment {
    assignmentID:       number;
    status:             null;
    bridgeID:           string;
    manualLevel:        number;
    published:          number;
    updated_by:         number | null;
    created_at:         null;
    updated_at:         null | string;
    hasSolution:        boolean;
    hasAnswer:          boolean;
    hasHint:            boolean;
    user_solution:      boolean;
    highlighted:        boolean;
    completedAt:        null;
    template_data:      TemplateData;
    assignmentVideoUrl: boolean;
    levels:             number[];
    level:              number;
    template_id:        number;
    title:              string;
    position:           number;
    assignment_id:      number;
    section_id:         number;
    points:             number;
    latest_status:      null;
    difficulty:         null;
    pivot:              SectionAssignmentRelation;
    assignment_content: AssignmentContent;
    solutions:          Solution[];
    hints:              Hint[];
}

export interface AssignmentContent {
    assignmentID:       number;
    templateID:         number;
    templateData:       string;
    title:              string;
    presentation_title: string;
    videoUrl:           null;
    image_id:           null;
    image:              null;
}

export interface Hint {
    id:           number;
    assignmentID: number;
    subtask:      Subtask | null;
    hints:        string;
    created_at:   string;
    updated_at:   string;
}

export enum Subtask {
    A = "a)",
    B = "b)",
    C = "c)",
    D = "d)",
    E = "e)",
}

export interface SectionAssignmentRelation {
    section_id:      number;
    assignment_id:   number;
    level:           number;
    assignment_name: string;
    position:        number;
    id?:             number;
}

export interface Solution {
    id:           number;
    assignmentID: number;
    subtask:      Subtask | null;
    solutions:    string;
    answers:      string;
    created_at:   string;
    updated_at:   string;
}

export interface TemplateData {
    text:                string;
    unit:                Unit;
    illustration:        null | string;
    responseType:        ResponseType;
    geolocation:         Geolocation;
    suggestion:          string;
    settings:            SettingsClass | string;
    variable?:           string;
    sign?:               string;
    "teacher-guide"?:    string;
    respons?:            Respon[];
    assignmentID?:       number;
    title?:              string;
    presentation_title?: string;
}

export enum Geolocation {
    Disable = "disable",
}

export interface Respon {
    value: string;
}

export enum ResponseType {
    Absolute = "absolute",
    Multiple = "multiple",
    Show = "show",
}

export interface SettingsClass {
    q1?:               string;
    u1?:               U1;
    q2?:               string;
    u2?:               U1;
    q3?:               string;
    u3?:               U1;
    q4?:               string;
    u4?:               U1;
    q5?:               string;
    u5?:               U1;
    q6?:               string;
    u6?:               U1;
    no_answer_button?: string;
    v1?:               string;
    v2?:               string;
    v3?:               string;
    v4?:               string;
    v5?:               string;
    v6?:               string;
}

export enum U1 {
    Empty = "",
    JaNej = "Ja/Nej",
}

export enum Unit {
    Empty = "",
    Kr = "kr",
    SidorPerDag = "sidor per dag",
}

export interface Lesson {
    id:         number;
    body:       string;
    created_at: string;
    updated_at: string;
    html:       string;
}

export interface Pivot {
    hierarchy_id: number;
    section_id:   number;
}
