// Generated by https://quicktype.io

export interface LessonRoot {
    content: Content;
}

export interface Content {
    chapters: Chapter[];
}

export interface Chapter {
    name:          string;
    hierarchyID:   number;
    max_level:     number;
    series:        number;
    isHidden:      boolean;
    user_progress: any[];
    sections:      Section[];
    parts?:        Chapter[];
    subParts?:     Chapter[];
}

export interface Section {
    id:                            number;
    name:                          string;
    lesson_id:                     number;
    created_at:                    string;
    updated_at:                    string;
    pivot:                         Pivot;
    lesson:                        Lesson;
    section_assignment_relations?: SectionAssignmentRelation[];
}

export interface Lesson {
    id:         number;
    body:       string;
    created_at: string;
    updated_at: string;
    html:       string;
}

export interface Pivot {
    hierarchy_id: number;
    section_id:   number;
}

export interface SectionAssignmentRelation {
    id:              number;
    section_id:      number;
    assignment_id:   number;
    assignment_name: number;
    level:           number;
    position:        number;
}
